### ISSUE TITLE
Color information for text / words characters

### ISSUE THREAD

**Issue by kreuzberger** [useblocks/libpdf#38]
For Tests i want to get color information from the pdf text.
This could be stored in the Char / Word / HorizontalLine model classes.
These informations are stored per Char in pdf.

How could this be added to the model in a "usable way"?
E.g a word (sum of chars) could get a color if all chars in the word have the same color.
A line could get a color if all words in the line have the same color
and so on.

As an alternative the model could be extended to get at least the words and from them get the color informations (per word or per char)

At least the graphicstate.ncolor should be stored to get the "foreground" color information or could the graphicstate of each LTChar be stored?

**Comment by ubmarco** [comment]
I like the idea and would go with the first model. Will check your PR.

**Comment by kreuzberger** [comment]
Close Issue after merge
